### ISSUE TITLE
Unable to install by Cocoapods

### ISSUE THREAD

**Issue by ttback** [toygard/youtube-parser#6]
Podfile: 

```
platform :ios, '7.0'
pod "youtube-parser", :git => 'https://github.com/toygard/youtube-parser.git'
```

Error:
pod install
Updating local specs repositories

CocoaPods 0.39.0.beta.3 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Pre-downloading: `youtube-parser` from `https://github.com/toygard/youtube-parser.git`
[!] Unable to satisfy the following requirements:
- `youtube-parser (from`https://github.com/toygard/youtube-parser.git`)` required by `Podfile`

**Comment by toygar-zzz** [comment]
You're right, I'm trying to fix it, thanks.

**Comment by davut5** [comment]
same problem for me. .
CocoaPods 0.39.0.beta.4 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
[!] Unable to satisfy the following requirements:
- `youtube-parser` required by `Podfile`

**Comment by davut5** [comment]
please fix it. Or can i install it manual.

**Comment by davut5** [comment]
https://github.com/toygard/youtube-parser/blob/master/youtube-parser.podspec  

burda deployment target 8.0 diyor. acaba bundan olabilir mi. 7.0 benim projem.

**Comment by toygar-zzz** [comment]
Swift support uses dynamic frameworks and is therefore only supported on iOS > 8.
